# Generated by Django 6.0.5 on 2026-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='siteFavIconLink',
            field=models.CharField(default='banana', max_length=100),
            preserve_default=False,
        ),
    ]
