# Generated by Django 6.0.5 on 2026-05-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_otp_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uid',
        ),
    ]
