# Generated by Django 6.0.5 on 2026-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_delete_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='uUid',
            field=models.CharField(default='10203023', max_length=10),
            preserve_default=False,
        ),
    ]
