# Generated by Django 6.0.5 on 2026-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_sitesettings_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
