# Generated by Django 6.0.5 on 2026-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_alter_adminuser_password_alter_adminuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='siteLink',
            field=models.CharField(default='http://127.0.0.1', max_length=100),
            preserve_default=False,
        ),
    ]
